# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65cdfddac991a2a7b0ff9128d50de83afd2d92d8b8490f7541e7caa649ec64d44df827827b3b934304c378e73ddb9b8386cb5334b807d6c317a89357af27780c
  user_name: "developerruby123@gmail.com"
  application_password: "cjodphxfhnsndujb"

test:
  secret_key_base: b7adae2af94577e062bedc4f0b28af17cd1dd75dcc483e20c80ffa1bb76599a81a887257affc10e98054b90b2dd45e9fba073a465a307ac9ff61d7eba6cb68b2
  user_name: "developerruby123@gmail.com"
  application_password: "cjodphxfhnsndujb"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  user_name: "developerruby123@gmail.com"
  application_password: "cjodphxfhnsndujb"
